services:

  rec-user-svc:
    build: ./rec-user-svc
    volumes: ["./artifacts:/data:ro"]

  ranker-svc:
    build: ./ranker-svc
    volumes: ["./artifacts:/data:ro"]
    environment:
      MODEL_PATH: "/data/ranker.pt"

  gateway-svc:
    build: ./gateway-svc
    volumes: ["./artifacts:/data:ro"]
    ports: ["8080:8000"]
    environment:
      REC_URL: "http://rec-user-svc:8000"
      RANK_URL: "http://ranker-svc:8000"
    depends_on: [rec-user-svc, ranker-svc]
